### ISSUE TITLE
CALYPSO5 - Complete Base ERC721 Sale Contract

### ISSUE THREAD

**Issue by TheGreatAxios** [mylilius/calypso-scavenger-hunt#5]

**Comment by TheGreatAxios** [comment]
# Todo

- [ ] Remove Empty Files
- [ ] Create Unit Testing for Sale
- [ ] Create Sale Base Contract

**Comment by TheGreatAxios** [comment]
# Todo
--
- [ ] Create Withdraw Tests (Sorry I Forgot)
- [ ] Create Withdraw Functions
